export function Hero() {
    return (
        <section>
            <h2>Welcome to SimplySports!</h2>
            <h3>Your one-stop shop for all things sports betting.</h3>
            <section id="hero-text">
                <p>
                    Whether you&apos;re a beginner or a pro, we have everything you need to get started and stay ahead of the game.
                    From the latest news and updates to in-depth tutorials and practice sessions, we&apos;ve got you covered. So what are you waiting for? Let&apos;s get started!
                </p>
            </section>
        </section>
    );
}

export function Features() {
    return (
        <section>
            <h2>Features</h2>
            <section>
                <ul>
                    <li>Keep up-to-date with all the major sports stories and news</li>
                    <li>Learn the ropes of sports betting, whether you&apos;re a beginner or a pro the learning never stops</li>
                    <li>Want to test your intuition or build that gut instint, head on over to the practice arena for a simulated betting session</li>
                </ul>
            </section>
        </section>
    );
}

export function Background() {
    return (
        <section>
            <h2>Background</h2>
            <p>
            According to Forbes, the Gambling industry brought in over 54.9 Billion USD in revenue during 2022. 
            From that 54.9 billion dollars, 7.5 billion dollars was generated by sports betting alone - accounting for roughly 13.7% of the total revenue generated. 

            In its entirety, Sports betting as a market has shown increased revenues of about 75% from 2021 to 2022 showing that more people are taking interest in the potential
            to make money off of sports betting.
            However, finding education on the topic proves to be extremely difficult. Only about 3-5% of sports bettors actually make profit off of their gambles, 
            meaning that the majority of general public tends to lose out. It is in the casinos and other Sports Betting franchises&apos; best interest to make sure that the public stays 
            relatively uneducated about how gambling on sports actually works in order to maximize profits which inevitably leads to many everyday people losing money.

            We here at SimplySports aim to provide a platform for users to enter the world of sports betting with a better understanding of the odds and the risks involved.
            To that end, we hope to even the playing field between users and the statistical disadvantages that they face when entering the world of sports betting.
            </p>
        </section>
    );
}
