import Container from '@mui/material/Container'
import Typography from '@mui/material/Typography'

export function Hero() {
    return (
        <>
        <Container
            sx={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                height: "100%",
            }}
            id="hero-container"
        >
            <Typography variant="h2" id="hero-title">
                Welcome to SimplySports!
                </Typography>
            <Typography variant="h5" id="hero-subtitle">
                An educational hub for all things sports betting
                </Typography>

            {/* <Container sx={{ padding: "15px" }} id="hero-divider-container">
                <Divider variant="middle" aria-hidden="true" flexItem/>
            </Container> */}

            <Typography variant="subtitle1" id="hero-content-body" align="center">
                Whether you&apos;re a beginner or a pro, we have everything you need to get started and enter the world of online betting.
                From current news & announcements to in-depth tutorials and lessons, we&apos;ve got you covered.
                </Typography>
            </Container>
        </>
    );
}

export function Features() {
    return (
        <>
        <Container
            sx={{
                display: 'flex',
                flexDirection: 'column',
                height: "100%",
            }}
            id="features-container"
        >
            <Typography variant="h4" id="features-title"
                sx={{
                    // border: '1px solid black',
                    // borderRadius: '15px',
                    // width: 'fit-content',
                }} 
            >
                Features
                </Typography>
            <Container id="features-list-container">
                <ul className="list-disc py-4">
                    <li>
                        <Typography variant="body1">
                            Sports News and Announcements: View major sports articles and announcements from various sites in one convenvient place. 
                            </Typography>
                        </li>
                    <li>
                        <Typography variant="body1">
                            Learn and improve: Forget what a money-line is? Want to learn how odds are calculated? Our learning academy has everything you need to clear any doubts and raise your betting confidence. 
                            </Typography>
                        </li>
                    <li>
                        <Typography variant="body1">
                            Simulated Practice: Want some practice before putting really money on the line? Try a practice match and see how good your gut-feeling is.
                            </Typography>
                        </li>
                    </ul>
                </Container>
            </Container>
        </>
    );
}

export function Background() {
    return (
        <>
        <Container
            sx={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'left',
                height: "100%",
            }} 
        >
            <Typography variant="h4" id="background-title" sx={{ paddingBottom: "5px"}}>
                Our Mission
                </Typography>
            <Typography variant="body1">
                According to Forbes, the Gambling industry earned over $54.9 Billion USD in revenue during 2022, of that, nearly $7.5 Billion was generated by sports betting alone. 
                However, only about 3-5% of sports bettors actually make profit off of their gambles, meaning a majority of people lose out. 
                </Typography>
                <br/>
            <Typography variant="body1">
                Raising awareness on the risky nature of online betting and the reality of the statistical disadvantages that users face is what Simply Sports is all about.
                By providing a platform that helps anyone learn the ins-and-outs of online betting, sports fans and gamblers alike can get a better sense of the odds and risks involved.
                </Typography>
            </Container>
        </>
    );
}

{/* <Typography variant="body1" id="background-content">
According to Forbes, the Gambling industry brought in over 54.9 Billion USD in revenue during 2022. 
From that 54.9 billion dollars, 7.5 billion dollars was generated by sports betting alone - accounting for roughly 13.7% of the total revenue generated. 

In its entirety, Sports betting as a market has shown increased revenues of about 75% from 2021 to 2022 showing that more people are taking interest in the potential
to make money off of sports betting.
However, finding education on the topic proves to be extremely difficult. Only about 3-5% of sports bettors actually make profit off of their gambles, 
meaning that the majority of general public tends to lose out. It is in the casinos and other Sports Betting franchises&apos; best interest to make sure that the public stays 
relatively uneducated about how gambling on sports actually works in order to maximize profits which inevitably leads to many everyday people losing money.

We here at SimplySports aim to provide a platform for users to enter the world of sports betting with a better understanding of the odds and the risks involved.
To that end, we hope to even the playing field between users and the statistical disadvantages that they face when entering the world of sports betting.
    </Typography>  */}

export function AboutUs() {
    return (
        <>
        <Container>
            <Typography variant="h4" id="about-us-title">
                About Us
                </Typography>
            <Typography variant="body1" id="about-us-content">
                Simply Sports was developed by a group of students from the University of Nevada-Reno, as a demonstration of
                the skills learned during the web development module of the Techwise program. Weekly check-ins and updates were 
                presented throughout the duration of the project, with a final presentation given to industry professionals after 3 months of development.
                </Typography>
            <br/>
            <Typography variant="body1" id="about-us-content">
                Techwise is a 12-month software development program ran by Talentsprint and sponsored by Google. A wide range of topics including web development, data structures & algorithms, and more
                were covered as part of the curriculum with group projects assigned at the end of each module.
                </Typography>
        </Container>
        </>
    )
}